{application,proccess_payments,
             [{modules,['Elixir.ProcessPayments',
                        'Elixir.ProcessPayments.DataProcessor',
                        'Elixir.ProcessPaymentsHandler']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"proccess_payments"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
